# Generated by Django 4.0.4 on 2022-05-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('slug', models.SlugField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='Umumiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=355)),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('aholi', models.BigIntegerField(default=0)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='viloyat.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('slug', models.SlugField(max_length=355)),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('aholi', models.BigIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='viloyat.viloyat')),
            ],
        ),
    ]
